### ISSUE TITLE
Game crashes when fighting with the ghosts on that level

### ISSUE THREAD

**Issue by joemaro** [crawl/crawl#1222]
**PLATFORM and OS or BROWSER:**
linux tiles client, trunk build 0.25-a0-241 (1 day old or so)

**DESCRIPTION:**
Game crashes when i open the ghost vault on that level and fight with the ghosts. It might be related to a spell issue or something, the 3 times it happened it seemed to be triggered by one of the ghosts casting a spell.

**EXTRA FILES:**
The zip file contains both the savegame and the crashlog.

[crashing savegame.zip](https://github.com/crawl/crawl/files/3917352/crashing.savegame.zip)

i can be reached on IRC ##crawl, joemaro

**Comment by ebering** [comment]
This was fixed in 0.25-a0-245. Thanks for the report.

**Comment by joemaro** [comment]
sorry for not pulling before the report.

just for completeness:

After i pulled and compiled, the game still crashed the first time i fought the ghosts, but didn't when i simply restarted it. Here's the crashlog in question:

[crash-Xijuci-20191203-165740.txt](https://github.com/crawl/crawl/files/3917515/crash-Xijuci-20191203-165740.txt)

**Comment by rawlins** [comment]
@joemaro thanks, this was still buggy and your save made it easy to diagnose. It should be fully fixed now.
